const list = [
    {
      id: 1,
      title: "O Vampiro que descobriu o Brasil",
      author: "Ivan Jaf",
      price: 89.00,
      img: "https://m.media-amazon.com/images/I/51DXuK1-ElL.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "O visitante inesperado",
      author: "Agatha Christie",
      price: 98,
      img: "https://d1pkzhm5uq4mnt.cloudfront.net/imagens/capas/_af779a02317d9bb26c114e80dc2dbd7c65fcf4d0.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "A Mansão Mollow",
      author: "Agatha Christie",
      price: 143,
      img: "https://m.media-amazon.com/images/I/A1EfZcI7XWL.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "A morte na Mesopotâmia",
      author: "Agatha Christie",
      price: 57,
      img: "https://m.media-amazon.com/images/I/81ibgyTIEYL.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Um convite para um homicídio",
      author: "Agatha Christie",
      price: 149,
      img: "https://m.media-amazon.com/images/I/71AK2W575wS.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Assassinato no expresso do oriente",
      author: "Agatha Christie",
      price: 135,
      img: "https://m.media-amazon.com/images/I/71gOOKU1chL.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Um corpo na biblioteca",
      author: "Agatha Christie",
      price: 693,
      img: "https://m.media-amazon.com/images/I/61T+S-cKcvL.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Os Elefantes não esquecem",
      author: "Agatha Christie",
      price: 289,
      img: "https://m.media-amazon.com/images/I/512a4o7xfzL._AC_SY780_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "A casa do penhasco",
      author: "Agatha Christie",
      price: 80,
      img: "https://www.lpm.com.br/livros/imagens/casa_do_penhasco__a_9788525420985_hd.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Os crimes ABC",
      author: "Agatha Christie",
      price: 86,
      img: "https://m.media-amazon.com/images/I/81rqjb5EIdL.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Morte no Nilo",
      author: "Agatha Christie",
      price: 120,
      img: "https://m.media-amazon.com/images/I/914zKRvyq7L.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Noite sem fim",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://m.media-amazon.com/images/I/81l9uOP-KhL.jpg",
      amount: 1,
    },
];

export default list;